function generate_trading_report(marketData, sentimentScores, results, coinSymbol)
% GENERATE_TRADING_REPORT Prints an executive summary and saves a performance report text file.

if nargin < 4 || isempty(coinSymbol), coinSymbol = 'ASSET'; end

% --- 1. Compute Key Strategy Metrics ---
stratEquity = results.StrategyEquity;
benchEquity = results.BenchmarkEquity;
signals     = results.Signals;

totalTrades = sum(abs(diff(signals)) > 0);
stratReturn = ((stratEquity(end) - stratEquity(1)) / stratEquity(1)) * 100;
benchReturn = ((benchEquity(end) - benchEquity(1)) / benchEquity(1)) * 100;
alpha       = stratReturn - benchReturn;

% Maximum Drawdown (Peak-to-Trough)
stratPeaks = cummax(stratEquity);
drawdowns  = (stratEquity - stratPeaks) ./ stratPeaks;
maxDrawdown = min(drawdowns) * 100;

% Dynamic Future Outlook based on Alpha & Sentiment
if alpha < -10
    statusStr = 'UNDERPERFORMING BENCHMARK';
    outlookStr = sprintf('The strategy currently trails buy-and-hold by %.2f%%. Consider tuning sentiment Z-score execution thresholds or adding a trend filter (e.g., 200 SMA) to reduce whipsaw trades.', abs(alpha));
elseif alpha > 5
    statusStr = 'OUTPERFORMING BENCHMARK';
    outlookStr = sprintf('Strategy is generating positive alpha (+%.2f%%). Dynamic execution triggers are capturing momentum effectively.', alpha);
else
    statusStr = 'NEUTRAL / TRACKING BENCHMARK';
    outlookStr = 'Strategy performance is closely tied to overall market beta. Risk exposure is managed, but upside capture is limited.';
end

% --- 2. Format Report Output ---
reportText = sprintf([ ...
    '=======================================================\n' ...
    '       QUANTITATIVE TRADING EXECUTIVE REPORT           \n' ...
    '=======================================================\n' ...
    ' Asset Symbol      : %s\n' ...
    ' Timestamp         : %s\n' ...
    ' Operational State : %s\n' ...
    '-------------------------------------------------------\n' ...
    ' PERFORMANCE SUMMARY\n' ...
    '-------------------------------------------------------\n' ...
    ' Total Trades Executed : %d trades\n' ...
    ' Strategy Net Return   : %.2f%%\n' ...
    ' Benchmark Return      : %.2f%%\n' ...
    ' Alpha vs Benchmark    : %.2f%%\n' ...
    ' Maximum Drawdown      : %.2f%%\n' ...
    '-------------------------------------------------------\n' ...
    ' FORWARD-LOOKING ASSESSMENT & RECOMMENDATIONS\n' ...
    '-------------------------------------------------------\n' ...
    ' %s\n' ...
    '=======================================================\n'], ...
    coinSymbol, datestr(now, 'yyyy-mm-dd HH:MM:SS'), statusStr, ...
    totalTrades, stratReturn, benchReturn, alpha, maxDrawdown, outlookStr);

% --- 3. Output to Console ---
fprintf('\n%s\n', reportText);

% --- 4. Export to Text File ---
fileName = sprintf('Trading_Report_%s.txt', coinSymbol);
fid = fopen(fileName, 'w');
if fid ~= -1
    fprintf(fid, '%s', reportText);
    fclose(fid);
    fprintf('[INFO] Report exported to: %s\n', fileName);
end
end